### ISSUE TITLE
Reset botton overflow

### ISSUE THREAD

**Issue by Wach-E** [Wach-E/Score-Keeper#1]
Hey! The UI of this page looks cool but unfortunately, the reset button overflows from the container when the site is opened in portrait mode of mobile device. If it can be fixed, I will be really grateful.

Here's the webpage: https://wach-e.github.io/Score-Keeper/

Thanks in advance.

**Comment by Smartech-git** [comment]
The problem was due to the misplacing of the div element. Starting from line  27 down to 44. 😀

**Comment by Wach-E** [comment]
The modifications from your PR was really helpful. Thank you @Smartech-git
